### PR TITLE
Fix defn of vector spaces, add linear maps/forms and inner product spaces

### PR DESCRIPTION
**Pull request by MithicSpirit**
- Fixes a bug in the previous definition of vector spaces
  - Alongside general improvements
- Defines (bi)linear maps/forms
  - TODO: n-linear maps/forms (seems annoying)
- Defines an inner product space (with inner product being a bilinear form with additional requirements)
  - Also defines abstract orthogonality

### CODE REVIEW

**Comment by MithicSpirit** [comment]
Closes #38

**Review by Anoushka1406 — COMMENTED** [review]
slay

**Review by Anoushka1406 — APPROVED** [review]
slay

**Review by Stavan-Jain — APPROVED** [review]
i guess

**Pull request merged**
